sudo: false
language: node_js
cache:
  directories:
  - node_modules
branches:
  only:
  - master
notifications:
  email: false
node_js:
- '4'
before_install:
- npm i -g npm@^2.0.0
before_script:
- npm prune
script:
- npm run coverage
- npm run check-coverage
after_success:
- npm run report-coverage
- npm run semantic-release
env:
  global:
  - SPHERE_PROJECT_KEY=sphere-product-type-import-test
  - secure: pQ81rNbn9gaF71h9NyYCVUTF/FeWxRFA1BP1aF2XjMu8bZ8yMCR1Jdi98qM8MY90NIMqF1ECc65cPIleBfsrpg7JQKKd+tSxVRkkZVoam3XQnvM6BCF3ZrN3CDuq7c2WPTEivKzHZofCrDgmumaqIqYynaCqYUjtchPHkO2QSY0OZ6W8ee8bvFkQvkIZL3BkkuUwum4PuZNV60saLyg+OyD2XKXBp8u78RNbNu5fmb4eIk3ogPNvKnN0TqgjRa3CkIrctcduadGvLwh3aHNUWyScUjEd2pe9R7i9jFpVQtka5eABUebR/daMBr5M/S06EIQiYHbC4Gq2ojBVNsNpbUHL+AuAnduLn1FSFZigN5sigLwDBgRD0tNVx32Aju2yyhwGwyQq/I2AjKw/VGC63Rvo7IGNhdBriZalZ4kv9V8vz5C1dbePP1u+Sm9IFb8yA6O7HzZ/aV6xh3Yf/MCZm4RFqhVQbkib0rR95ib1U/GQ2R7N5Es9o2E8sX8WFszR6n0k4NF7JsQS7roQRDDVfkQxedyfnb6xD3TfYHk25dypiqSFZ8lKByLstzihU9WbNah+MSfj73uOK+olTEwAh3FiV9bhvgqV5FGGgCZ0QLgEePBZlvtImqJ7wR5/22cPMFLo/LKHcZPbEcx2v/GzaIApEXQLsORMkFGS9RS5A9A=
  - secure: XO7/BiKlqhy8p7/9g4w9JAypp3t4NGDWxcbIu0jhl+UjqUKiMY6Qjq4h3w+cZC2SeX+FnxIkzdPYFnscAUmsMnRUXdGQMqegwNiCoeybQjIBD5J9+DHMiEOZoh5liJYkApk/O+sYG9XbPa89PoyoTxTS2MLbQOVmqrpJtpDWb6hOjl39x0iUDqO6ZkPTzWGiQcCij5BmAQOoHalgSsbdshaYJgoOiCVmKmj72aPplgvq3Ob1vgP/NTh8JesXeCNiN9cdP6kCb6SYQtioED9oH8D6t4h9qJUxIvf30+GA1RXXFkyMwym37SU10jotyhWmnjKE+7Q6xaQGpu7XfyIzcl98+X0bbl/LoAmBBtQBFHAhF5UyBDrpmzzRs+zi5NGHPHpuGUHbPawmpjFw/QVQIjWxw3zBkbjGfIQsPqlHMmaGRTrQ4d72JQXk/Kk1dlYLchCVl9gfA0BwO0EVGl3qdxf+TSAgLoOqbqhdSc8KfES7ZN8keViwxtV6fqDkwkubh9eX0H/iIfIL3tUH8Au9dFBrxGpNkabridqWwV070UWDKXHfrn6qhnYfumRZfDrOVvMhopUze0O/saxC9R9daEhsOZaNBVXNR8+OkGJu3KWClSZaowX+UdANItU8YXZYCa+4rUA74Q1H3X9JqIjfJnNg2aJTJI8gCAJgN88Vxsg=
  - secure: HCC+EDDltvRbGPkSI15+PXBB7PETSqUc3NdcSL+0JehfdbA9H1j8tu7GAWwf7A7a0fcREmKfmRZFwIOs3uMkM6v0ZkMVEav7aNef728p1rdUX5Nfp6rtDibW0w4kNXrRPIaUPMg4d7FWej8JLvdY8FH38/TcSQk2BqdSm86v8AFK+muWhRFMwGEzRToxH+b7T+rcgSxhUAa7fNseohXIWhsPA5lAxyM+JN+q55ZcOwzovoRjbiFchTdxIjR8kAEyUpftdOTdEReynQKwOxRnEHL1Vv7A85dTIZ5avRmU3rTatcRJ27dL0QgsPFqW71TjUevcnT0CIQzqsMTq5d80WFkF/l2SD/iKiMgd9MzbJLDJAViEe8JLhMhOos7SKGrNGPdgSBBhtMIDKlSYZU74Q49WNJPNqdOGC9JxAyqOYSrgP4w7bgWK+7XSKAjGTrvBUaeUSyKb4DWlLrzn6rjlomjg4ikeGV051ligm9VlPeZeuyu1axLc4bc2KYzeMsvz/dyfNygafIBzDJxr8ikNUixdDknY1ho5qhSnsKH4cwfbqQUAt5RZaXZ1NDdP4wsJjHL7Dk0PRZkX6BCiCXomZfkj6+kTzjePXKnRkK+/yCpXY3Y/rSYmX+0uXSqOrCkZlJBYz09IQ8LoLotIdfb8pSK//Fdy9GYCP9otoSx/+wc=
  - secure: CpcJ38kzOfP/XvzzpI7JC5WLkrrOlAwCSVdkt7FvgaaYISe8nO97Vze0k3YvLzZi423y3ZAxz5T9OEnbzSlWKB5K04e4zQp/HhVvNiEl5Fn3BOlEO8ZQu8J0zBAvKw9Wo8r9l3e5hZLv9Ip90F3Kra08QxLE+r2RwJCpXvFvgEml906Oa+mIoLsmyFgQfRhREQgVgkKKG2cozGSg7Ti4gWBYzmW5OXexijMPyIcaTcSMSqkFQWQC153cc5gM4JsCHPVXizaV7hnua9CGrjmnX1iTk89zoo0EVW2ByFyq9DNLuMeBpDwpNJjTJtGuXHgMnscxV5iRlSNAxvU6lKRuIRPyCGd4Su42PbvF2/lnjq8mVdZQCKh14HeWa4M4Ta1YYRP0lnCM56rd/iblkc6C/UK8aFQ4LM0b2IRS6LT6Rur/1/E34dsP1ugZ9FKJoFNOcebQpFVGBoYpMIvHBfGFDyrxEZVXmyrADmE+M/o7FfMsLDxIlrewhgwC4malpsbGHNTsS2rExyKFCZgmWSdUiJBUjkPI+nqlhyGJt0F3iEag+3CMsuOgPDbqk0sIFN5rzX51VXVCOzFAo1sThxNF4zMKA1gjBc2V9RQd3Kifmuknv6DgbyxBLktcfecxT3Lii5IEGnzObVLiNYWcil1816d0+dJNAUEyJtR4TODR5/M=
